#!/usr/bin/env python3
"""
Main confrm server.

Kicks off a single thread unvicorn instance. Single thread to enable the
use of the simple tinydb database engine.

Copyright 2020 Confrm.io

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""


import argparse
import os
import toml
import uvicorn


def check_config_file(config):
    """Check that the config file contains the required fields"""

    elements = ["basic", "storage"]
    for element in elements:
        if element not in config.keys():
            raise Exception(f"Config does not contain '{element}' element")
    basic_names = ["port"]
    for name in basic_names:
        if name not in config["basic"].keys():
            raise Exception(
                f"Config element 'basic' does not contain '{name}'"
            )
    storage_names = ["data_dir"]
    for name in storage_names:
        if name not in config["storage"].keys():
            raise Exception(
                f"Config element 'storage' does not contain '{name}'"
            )

    # Additional checks based on data content
    if os.path.exists(config["storage"]["data_dir"]) is False:
        raise Exception(
            f"'data_dir' {config['storage']['data_dir']}does not exists"
        )


def main():
    """It is the main method, here's to pylint nirvana"""

    parser = argparse.ArgumentParser(description="confrm Server Application")
    parser.add_argument("--config", type=str, help="Path to config.toml")
    args = parser.parse_args()

    if os.path.isfile(args.config) is False:
        raise Exception("Config file does not exists")

    config = toml.load(args.config)
    check_config_file(config)

    os.environ["CONFRM_CONFIG"] = args.config

    # Important that workers = 1 in order to use tinydb, more than one
    # worker may cause issues working with information in the db.
    uvicorn.run(
            "confrm:APP",
            host="10.0.1.106",
            workers=1)

if __name__ == "__main__":
    main()
